### ISSUE TITLE
Add opensource license and copyright

### ISSUE THREAD

**Issue by hadesto** [pr-holonet/pr-holonet#8]
add opensource license to repo and copyright

**Comment by ewanmellor** [comment]
Are you OK with BSD license?

**Comment by hadesto** [comment]
Ideally I'd like a license that : 
1) does not make us responsible for whatever people build out of this. 
2) keeps it open source
3) ensures attribution
4) makes no guarantees of it working 

AKA keep it open source, help as many people as possible, keep track of where the original repo is (so people can contribute to it),  and that if someone tries to build something critical and it doesn't work we don't have people hounding our doors.

**Comment by hadesto** [comment]
not sure what the options are or what exactly BSD entails so i'll have to do some reading about it.

**Comment by ewanmellor** [comment]
BSD: https://opensource.org/licenses/BSD-2-Clause.  This would allow other people to make commercial products out of it, but would otherwise meet your meet your bullets (depending on what you mean by bullet 2).  It is the lowest-hassle of all the licenses.

If by bullet 2 you mean "I don't want people to include this in commercial products without giving us their changes back" then you want GPL: https://opensource.org/licenses/GPL-2.0.  Personally though, I'd recommend not using GPL for this -- we have a very small amount of code, so if some BigCorp wants to replicate this then they'll just rewrite what we've done, and GPL otherwise dis-incentivizes a BigCorp from getting involved (if that ever becomes a possibility).

Apache: https://opensource.org/licenses/Apache-2.0.  This is a good middle-ground option.  It allows commercial exploitation as long as there is some attribution (like BSD) but it covers some of the more legalesey issues, like patents.  It's a good option too (especially for large projects where you're expecting to take submissions from other people and patents might be an issue).

Personally I don't expect we'll have any such issues, and BSD would be just fine.

**Comment by hadesto** [comment]
license added. closing issue
